import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge'}),page=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});
try{
 for(const [name,width] of [['escritorio',1280],['movil',390]]){await page.setViewportSize({width,height:900});await page.goto(base+'index.html');await page.evaluate(async()=>{document.documentElement.style.scrollBehavior='auto';await document.fonts.ready;const img=document.querySelector('.halloween-art img');img.loading='eager';await img.decode();const e=document.querySelector('.halloween-special');scrollTo(0,e.getBoundingClientRect().top+scrollY-90)});await page.waitForTimeout(200);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const web=page.locator('.halloween-special>.seasonal-web');assert.equal(await web.evaluate(e=>getComputedStyle(e).opacity),'0.58');assert.equal(await web.evaluate(e=>getComputedStyle(e).pointerEvents),'none');const r=await web.boundingBox();await page.screenshot({path:'qa-output/AKME-telarana-'+name+'.png',clip:{x:Math.max(0,r.x-90),y:Math.max(0,r.y-30),width:Math.min(width,r.width+90),height:r.height+170}});console.log('PASS visible web '+name);}
 await page.addInitScript(()=>{const original=Element.prototype.animate;Element.prototype.animate=function(...args){const a=original.apply(this,args);if(this.classList.contains('visual-curtain')){a.pause();a.currentTime=150;window.frozenCurtain=a;}return a;};});
 await page.setViewportSize({width:1280,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(base+'index.html');await page.locator('.nav a[href="servicios.html"]').click();await page.waitForURL('**/servicios.html');await page.waitForFunction(()=>!!window.frozenCurtain);const ghost=await page.locator('.visual-curtain').evaluate(e=>({background:getComputedStyle(e,':after').backgroundImage,duration:window.frozenCurtain.effect.getTiming().duration}));assert(ghost.background.includes('svg'));assert.equal(ghost.duration,420);const b=await page.locator('.visual-curtain').boundingBox();await page.screenshot({path:'qa-output/AKME-fantasma-transicion.png',clip:{x:Math.max(0,b.x-90),y:200,width:200,height:180}});console.log('PASS actual ghost transition frame; real duration 420ms');
}finally{await browser.close();server.close();}
