import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge'}),context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:'qa-output/motion-fix-video',size:{width:1280,height:720}}}),page=await context.newPage();
async function load(file){await page.goto(base+file);await page.evaluate(async()=>{document.documentElement.style.scrollBehavior='auto';for(const i of document.images)i.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await document.fonts.ready;});}
async function caption(text){await page.evaluate(text=>{let e=document.querySelector('#qa-caption');if(!e){e=document.createElement('div');e.id='qa-caption';e.style.cssText='position:fixed;inset:12px auto auto 50%;transform:translateX(-50%);z-index:99999;background:#111;color:#d5f63f;border-radius:22px;padding:10px 22px;font:15px Arial;white-space:nowrap;pointer-events:none';document.body.append(e)}e.textContent=text},text);}
try{
 await load('index.html');await caption('Paquetes abre desde su introducción');await page.locator('.nav a').filter({hasText:/^Paquetes$/}).click();await caption('Paquetes abre desde su introducción');await page.waitForTimeout(2400);
 await load('index.html');await caption('Generamos impacto · letras más suaves · automático cada 6 s');await page.locator('.impact-message').evaluate(e=>e.scrollIntoView({block:'center'}));await page.waitForTimeout(8800);
 await load('servicios.html');for(const [i,label] of ['Idea · el concepto toma forma','Producción · se construye la cámara','Edición · estructura, bloques y recorrido'].entries()){await caption(label);await page.locator('#concept-step-'+i+' .process-graphic').evaluate(e=>e.scrollIntoView({block:'center'}));await page.waitForTimeout(i===2?6500:3600);}
 await caption('Cierre AKME · automático cada 6 s · sin botón de repetición');await page.evaluate(()=>scrollTo(0,document.body.scrollHeight));await page.waitForTimeout(8500);
 await page.screenshot({path:'qa-output/motion-fix-footer.png'});
}finally{const video=page.video();await context.close();await video.saveAs('qa-output/akme-ajustes-motion.webm');await browser.close();server.close();}
