import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.mp3':'audio/mpeg'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge'}),context=await browser.newContext({viewport:{width:1280,height:900},recordVideo:{dir:'qa-output/halloween-video',size:{width:1280,height:900}}});const origin=Date.now(),page=await context.newPage();let start=0,soundStart=0;
await page.addInitScript(()=>{const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.demoAudio=a;return a;};});
async function ready(){await page.evaluate(async()=>{document.documentElement.style.scrollBehavior='auto';for(const img of document.images)img.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await document.fonts.ready;});}
try{
 await page.goto(base+'index.html');await ready();await page.mouse.move(700,80);start=(Date.now()-origin)/1000;await page.waitForTimeout(2000);await page.locator('.sound-yes').click();await page.locator('.halloween-art').evaluate(e=>e.scrollIntoView({block:'center'}));await page.waitForFunction(()=>window.demoAudio&&!demoAudio.paused&&demoAudio.currentTime>.01);soundStart=(Date.now()-origin)/1000-await page.evaluate(()=>demoAudio.currentTime);await page.locator('.halloween-special').evaluate(e=>scrollTo(0,e.getBoundingClientRect().top+scrollY-90));await page.waitForTimeout(13500);await page.screenshot({path:'qa-output/AKME-Halloween-integrado-escritorio.png'});
 await page.locator('.nav a[href="servicios.html"]').click();await page.waitForURL('**/servicios.html');await page.waitForTimeout(1400);await page.locator('.nav a[href="planes.html"]').click();await page.waitForURL('**/planes.html');await page.waitForTimeout(1400);await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,document.body.scrollHeight)});await page.waitForTimeout(7500);
 fs.writeFileSync('qa-output/halloween-video-timing.json',JSON.stringify({start,soundStart,end:(Date.now()-origin)/1000}));
}finally{const v=page.video();await context.close();await v.saveAs('qa-output/AKME-Halloween-integrado-raw.webm');}
const mobile=await browser.newPage({viewport:{width:390,height:1100},reducedMotion:'reduce'});try{await mobile.goto(base+'index.html');await mobile.evaluate(async()=>{document.documentElement.style.scrollBehavior='auto';for(const i of document.images)i.loading='eager';await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));await document.fonts.ready;const e=document.querySelector('.halloween-special');scrollTo(0,e.getBoundingClientRect().top+scrollY-90)});await mobile.waitForTimeout(300);await mobile.screenshot({path:'qa-output/AKME-Halloween-integrado-movil.png'});}finally{await browser.close();server.close();}
