import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.mp3':'audio/mpeg'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',args:['--autoplay-policy=document-user-activation-required']});let errors=[];
async function fresh(width,silent=false){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),p=await context.newPage();await context.route(/fonts\.(googleapis|gstatic)\.com/,r=>r.abort());p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(silent=>{if(silent)sessionStorage.setItem('akme:halloween-sound-choice','silent');const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.testAudio=a;window.playCalls=0;const play=a.play.bind(a);a.play=()=>{playCalls++;return play()};return a;};},silent);return{context,p};}
async function noGesture(p,expression){const c=await p.context().newCDPSession(p);try{const r=await c.send('Runtime.evaluate',{expression,userGesture:false,returnByValue:true,awaitPromise:true});return r.result.value;}finally{await c.detach();}}
async function go(p,file='index.html'){await p.goto(base+file,{waitUntil:'domcontentloaded'});await noGesture(p,"document.documentElement.style.scrollBehavior='auto'");}
async function section(p){await noGesture(p,"document.querySelector('.halloween-art').scrollIntoView({block:'center'})");await p.waitForTimeout(180);}
async function attempted(p){for(let i=0;i<30;i++){if(await noGesture(p,"playCalls===1&&(!testAudio.paused||document.querySelector('.halloween-laugh-status').textContent.includes('Tocá'))"))return;await p.waitForTimeout(100);}throw new Error('No settled section play attempt');}
try{
 for(const width of [1440,390]){
  let {context,p}=await fresh(width);let downloads=0;p.on('request',r=>{if(r.url().includes('halloween-laugh.mp3'))downloads++});await go(p);assert.equal(await noGesture(p,"document.querySelectorAll('.halloween-welcome,.sound-yes,.sound-no').length"),0);assert.equal(downloads,0);assert.equal(await noGesture(p,'playCalls'),0);await section(p);await attempted(p);assert.equal(await noGesture(p,'navigator.userActivation.hasBeenActive'),false);assert(await noGesture(p,'testAudio.paused'),'Real browser blocks scroll-only audio');assert(await p.locator('.halloween-laugh-play').isVisible());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:'qa-output/AKME-audio-automatico-'+width+'.png'});
  await p.locator('.halloween-laugh-play').click();await p.waitForFunction(()=>!testAudio.paused&&testAudio.currentTime>.05);assert.equal(await p.evaluate(()=>testAudio.volume),.35);assert.equal(await p.evaluate(()=>testAudio.loop),false);await p.locator('.halloween-sound-control').click();assert(await p.evaluate(()=>testAudio.paused));assert.equal(await p.evaluate(()=>sessionStorage.getItem('akme:halloween-sound-choice')),'silent');await p.locator('.halloween-sound-control').click();await p.waitForFunction(()=>!testAudio.paused);await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert(await p.evaluate(()=>testAudio.paused));await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert(await p.evaluate(()=>testAudio.paused));await p.locator('.halloween-sound-control').click();await p.waitForFunction(()=>testAudio.ended,{},{timeout:15000});assert(await p.evaluate(()=>testAudio.currentTime>=9.4&&testAudio.duration<9.7));const count=await p.evaluate(()=>playCalls);await p.evaluate(()=>scrollTo(0,0));await section(p);assert.equal(await p.evaluate(()=>playCalls),count);await p.reload({waitUntil:'domcontentloaded'});await section(p);assert.equal(await p.evaluate(()=>playCalls),0);await context.close();console.log('PASS no question; real scroll-only autoplay block and contextual fallback; full audio/mute/hidden/reload '+width);
  ({context,p}=await fresh(width));await go(p);await p.locator('.home-character').click();assert.equal(await p.evaluate(()=>playCalls),0);await section(p);await attempted(p);assert(!(await p.evaluate(()=>testAudio.paused)),'Prior normal click permits playback in this browser');assert.equal(await p.evaluate(()=>playCalls),1);await context.close();console.log('PASS prior normal click then automatic section playback '+width);
  ({context,p}=await fresh(width,true));await go(p);await section(p);assert.equal(await p.evaluate(()=>playCalls),0);assert.match(await p.locator('.halloween-laugh-status').textContent(),/desactivado/);await p.reload({waitUntil:'domcontentloaded'});await section(p);assert.equal(await p.evaluate(()=>playCalls),0);await context.close();console.log('PASS persisted silence '+width);
  ({context,p}=await fresh(width));await go(p,'index.html#halloween');await section(p);await attempted(p);assert(await p.evaluate(()=>testAudio.paused));assert(await p.locator('.halloween-laugh-play').isVisible());await context.close();console.log('PASS direct entry contextual fallback '+width);
 }
 const {context,p}=await fresh(1440);await go(p,'servicios.html');await p.locator('.nav a[href="index.html"]').click();await p.waitForURL('**/index.html');await section(p);await attempted(p);console.log('PASS navigation then section; browser result '+(await p.evaluate(()=>testAudio.paused?'blocked with fallback':'playing')));await context.close();assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}
