import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.mp3':'audio/mpeg'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
let navCount=0;const go=async file=>{const url=new URL(file,base);url.searchParams.set('audio_test',String(++navCount));await page.goto(url.href,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
 let requested=0;page.on('request',r=>{if(r.url().includes('halloween-laugh.mp3'))requested++});
 await page.addInitScript(()=>{const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.testAudio=a;window.playCalls=0;const play=a.play.bind(a);a.play=()=>{window.playCalls++;if(window.blockNextPlay){window.blockNextPlay=false;return Promise.reject(new DOMException('User gesture required','NotAllowedError'));}return play();};return a;};});
 const clear=()=>page.evaluate(()=>{sessionStorage.removeItem('akme:halloween-sound-choice');sessionStorage.removeItem('akme:halloween-laugh-played');});
 const section=async()=>{await page.locator('.halloween-art').evaluate(e=>e.scrollIntoView({block:'center'}));await page.waitForTimeout(150);};
 await go('index.html');
 for(const width of [1440,390]){
  await clear();await page.setViewportSize({width,height:900});await go('index.html');let n=requested;await page.locator('.sound-yes').click();assert(await page.evaluate(()=>testAudio.paused));assert.equal(requested,n,'No entry audio before section');await section();await page.waitForFunction(()=>!testAudio.paused&&testAudio.currentTime>.05);assert.equal(await page.evaluate(()=>playCalls),1);assert.equal(await page.evaluate(()=>testAudio.loop),false);assert.equal(await page.evaluate(()=>testAudio.volume),.35);
  await page.locator('.halloween-sound-control').click();assert(await page.evaluate(()=>testAudio.paused));const pos=await page.evaluate(()=>testAudio.currentTime);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>testAudio.currentTime),pos);await page.locator('.halloween-sound-control').click();await page.waitForFunction(()=>!testAudio.paused);
  await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.evaluate(()=>testAudio.paused));await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert(await page.evaluate(()=>testAudio.paused));await page.locator('.halloween-sound-control').click();await page.waitForFunction(()=>testAudio.ended,{},{timeout:15000});assert(await page.evaluate(()=>testAudio.currentTime>=9.4&&testAudio.duration<9.7));let count=await page.evaluate(()=>playCalls);await page.evaluate(()=>scrollTo(0,0));await section();assert.equal(await page.evaluate(()=>playCalls),count,'No repeat on section reentry');await page.reload({waitUntil:'domcontentloaded'});await section();assert.equal(await page.evaluate(()=>playCalls),0,'No repeat on reload');assert.equal(await page.locator('.halloween-laugh-play').isVisible(),false);
  await clear();await go('index.html');n=requested;await page.locator('.sound-no').click();await section();assert.equal(requested,n,'Silence respected without downloading audio');assert(await page.evaluate(()=>testAudio.paused));assert.match(await page.locator('.halloween-laugh-status').textContent(),/sin sonido/);await page.reload({waitUntil:'domcontentloaded'});await section();assert.equal(requested,n);assert.equal(await page.evaluate(()=>playCalls),0);console.log('PASS section consent/silent/reload/full audio/one play/hidden/mute '+width);
 }
 await clear();await go('index.html#halloween');await section();assert.equal(await page.evaluate(()=>playCalls),0);assert(await page.locator('.halloween-laugh-play').isVisible());await page.locator('.halloween-laugh-play').click();await page.waitForFunction(()=>!testAudio.paused);await page.locator('.halloween-sound-control').click();console.log('PASS direct section entry offers explicit control');
 await clear();await go('index.html');await page.evaluate(()=>window.blockNextPlay=true);await page.locator('.sound-yes').click();await section();await page.waitForFunction(()=>document.querySelector('.halloween-laugh-status').textContent.includes('Tocá'));assert(await page.evaluate(()=>testAudio.paused));assert(await page.locator('.halloween-laugh-play').isVisible());await page.locator('.halloween-laugh-play').click();await page.waitForFunction(()=>!testAudio.paused);await page.locator('.halloween-sound-control').click();console.log('PASS simulated browser autoplay rejection recovers with contextual gesture');
 await clear();await go('index.html');await page.evaluate(()=>sessionStorage.setItem('akme:halloween-sound-choice','sound'));await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('.halloween-welcome').count(),0);await section();await page.waitForFunction(()=>!testAudio.paused);await page.locator('.halloween-sound-control').click();console.log('PASS returning legacy consent reaches section without losing controls');
 for(const width of [320,390,1440]){await clear();await page.setViewportSize({width,height:900});await go('index.html#halloween');await section();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'qa-output/AKME-risita-en-gato-'+width+'.png'});}
 const n=requested;await go('planes.html');assert.equal(await page.locator('.halloween-laugh,.halloween-welcome,.halloween-sound-control').count(),0);assert.equal(requested,n);assert.deepEqual(errors,[]);console.log('PASS other pages silent; responsive; no JS errors');
}finally{await browser.close();server.close();}
