import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const file of ['index.html','portafolio.html','servicios.html','planes.html']){
  await go(file);assert(await page.evaluate(()=>document.documentElement.classList.contains('akme-halloween')));assert.equal(await page.locator('.seasonal-web').count(),2);assert.equal(await page.locator('.camera-cue').textContent(),'¡Boo! Sonreí');await page.locator('.camera-figure img').evaluate(i=>i.decode());assert((await page.locator('.camera-figure img').getAttribute('src')).includes('akme-ghost.png'));
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('.message-replay,.impact-replay').count(),0);
  for(const y of [0,1000,99999]){await page.evaluate(y=>scrollTo(0,y),y);await page.waitForTimeout(100);assert(await page.locator('.seasonal-web').evaluateAll(es=>es.every(e=>getComputedStyle(e).pointerEvents==='none')));const box=await page.locator('.quote-mascot').boundingBox();assert(box.x>=0&&box.x+box.width<=width+1&&box.y>=0&&box.y+box.height<=901);}
  if(width<760){await page.locator('#menu-btn').click();assert(await page.locator('#navigation-dialog').evaluate(e=>e.open));assert(!(await page.locator('.quote-mascot').isVisible()));await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#navigation-dialog').open);assert(await page.locator('#menu-btn').evaluate(e=>e===document.activeElement));}
  if(file==='index.html'){assert.equal(await page.locator('.halloween-special').count(),1);assert(await page.locator('.halloween-special').evaluate(e=>e.nextElementSibling.classList.contains('showreel')));await page.locator('.halloween-art img').evaluate(i=>{i.loading='eager';return i.decode()});assert((await page.locator('.halloween-cta').getAttribute('href')).startsWith('https://wa.me/59157385254'));const fit=await page.locator('.halloween-art img').evaluate(img=>{const r=img.getBoundingClientRect(),box=img.parentElement.getBoundingClientRect(),scale=Math.min(r.width/img.naturalWidth,r.height/img.naturalHeight),left=r.left+(r.width-img.naturalWidth*scale)/2,top=r.top+(r.height-img.naturalHeight*scale)/2;return {left:left+170*scale-box.left,right:left+1042*scale-box.left,top:top+212*scale-box.top,bottom:top+1225*scale-box.top,width:box.width,height:box.height}});assert(fit.left>=-1&&fit.top>=-1&&fit.right<=fit.width+1&&fit.bottom<=fit.height+1,'Complete silhouette fits '+JSON.stringify(fit));}
 }console.log('PASS Halloween pages/geometry/menu '+width);}
 await page.addInitScript(()=>{window.entryEffects=[];const original=Element.prototype.animate;Element.prototype.animate=function(...args){if(this.classList.contains('visual-curtain'))entryEffects.push({duration:args[1].duration,ghost:getComputedStyle(this,':after').backgroundImage});return original.apply(this,args)}});
 await page.setViewportSize({width:1440,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await go('index.html');await page.locator('.nav a').filter({hasText:/^Paquetes$/}).click();await page.waitForURL('**/planes.html');await page.waitForFunction(()=>window.entryEffects.length===1);assert.equal(await page.evaluate(()=>entryEffects[0].duration),420);assert((await page.evaluate(()=>entryEffects[0].ghost)).includes('svg'));assert.equal(await page.evaluate(()=>location.hash),'');await page.waitForTimeout(500);assert.equal(await page.locator('.visual-curtain').count(),0);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.nav a[href="servicios.html"]').click();await page.waitForURL('**/servicios.html');await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>entryEffects.length),0);assert.equal(await page.locator('.camera-figure').evaluate(e=>e.getAnimations().length),0);console.log('PASS brief native ghost transition; reduced motion static');
 await page.route('**/seasonal-config.js*',route=>route.fulfill({contentType:'text/javascript',body:"window.AKME_SEASON={enabled:false,theme:'halloween'};"}));await go('index.html');assert.equal(await page.locator('.halloween-special,.seasonal-web,.seasonal-pet').count(),0);assert.equal(await page.locator('.camera-cue').textContent(),'Sonríe');assert((await page.locator('.camera-figure img').getAttribute('src')).includes('akme-cat.webp'));assert(!(await page.evaluate(()=>document.documentElement.classList.contains('akme-halloween'))));console.log('PASS single-switch restoration to regular site');assert.deepEqual(errors,[]);
}finally{await browser.close();server.close();}
