import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
 await page.addInitScript(()=>{window.entryMotionCount=0;const animate=Element.prototype.animate;Element.prototype.animate=function(...args){if(this.id==='gallery-viewer')entryMotionCount++;return animate.apply(this,args)}});
 await page.emulateMedia({reducedMotion:'no-preference'});await go('portafolio.html');await page.locator('#proyecto-spadental .gallery-card[data-index="0"]').click();assert(await page.evaluate(()=>entryMotionCount>=1));await page.waitForTimeout(300);assert(await page.locator('.gallery-close').evaluate(e=>document.activeElement===e));await page.locator('.gallery-close').click();await page.waitForFunction(()=>!document.querySelector('#gallery-viewer').open);
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),tp=await context.newPage();await tp.goto(base+'portafolio.html');await tp.locator('#proyecto-spadental .gallery-card[data-index="0"]').tap();await tp.locator('#gallery-media img').evaluate(e=>e.decode());assert.equal(await tp.locator('#gallery-viewer').evaluate(e=>e.getAnimations().length),0);
 const box=await tp.locator('#gallery-media img').boundingBox(),cdp=await context.newCDPSession(tp),cx=box.x+box.width/2,cy=box.y+box.height/2;
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx-35,y:cy,id:0},{x:cx+35,y:cy,id:1}]});for(let i=1;i<=5;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx-35-i*10,y:cy,id:0},{x:cx+35+i*10,y:cy,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 assert(await tp.locator('#gallery-media').evaluate(e=>e.classList.contains('is-zoomed')),'Pinch zoom');assert.equal(await tp.locator('#gallery-count').textContent(),'1 de 5','Pinch does not swipe');await tp.getByRole('button',{name:'Restablecer zoom',exact:true}).tap();assert.equal(await tp.getByRole('button',{name:'Restablecer zoom',exact:true}).textContent(),'100%');
 await tp.getByRole('button',{name:'Acercar imagen',exact:true}).tap();const before=await tp.locator('#gallery-media img').evaluate(e=>e.style.transform);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:cx,y:cy,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:cx+30,y:cy+25,id:0}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await tp.locator('#gallery-media img').evaluate(e=>e.style.transform),before,'Drag pan');await tp.screenshot({path:'qa-output/gallery-zoom-mobile.png'});await tp.locator('#gallery-next').tap();await tp.waitForFunction(()=>document.querySelector('#gallery-count').textContent==='2 de 5');assert.equal(await tp.getByRole('button',{name:'Restablecer zoom',exact:true}).textContent(),'100%');await tp.locator('.gallery-close').tap();await context.close();
 await go('index.html');await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.waitForTimeout(550);const timings=await page.locator('.impact-phrase,.footer-contact').evaluateAll(es=>es.map(e=>e.getAnimations().map(a=>a.effect.getTiming())));assert.equal(timings.length,2);assert.equal(timings[0][0].delay,700);assert.equal(timings[1][0].delay,780);await page.waitForTimeout(1500);assert(await page.locator('.impact-phrase,.footer-contact').evaluateAll(es=>es.every(e=>getComputedStyle(e).opacity==='1'&&e.getAnimations().length===0)));await page.locator('.impact-replay').click();assert.equal(await page.locator('.impact-phrase').evaluate(e=>e.getAnimations().length),1);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>[...document.querySelectorAll('.impact-phrase,.footer-contact')].every(e=>e.getAnimations().length===0));assert(await page.locator('.impact-phrase,.footer-contact').evaluateAll(es=>es.every(e=>getComputedStyle(e).opacity==='1'&&e.getAnimations().length===0)));assert.deepEqual(errors,[]);console.log('PASS identity entry, connected transition/reduced fallback, focus, mobile pinch/pan/reset, no pinch swipe, media reset, synchronized footer 700/780ms, replay, reduced motion.');
}finally{await browser.close();server.close();}
