import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
 const pages=[['index.html','zorro'],['portafolio.html','panda'],['servicios.html','mapache'],['planes.html','conejo']];
 for(const width of [320,390,430,1366])for(const [file,animal] of pages){await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await go(file);const pet=page.getByRole('button',{name:'Animar '+animal,exact:true});await pet.waitFor();assert.equal(await page.locator('.mascot-reactive').count(),1);assert.equal(await pet.evaluate(e=>e.getAnimations().length),0,'No automatic gesture');await pet.focus();await page.keyboard.press('Enter');assert.equal(await pet.evaluate(e=>e.getAnimations().length),1);await page.waitForTimeout(700);await page.keyboard.press('Space');assert.equal(await pet.evaluate(e=>e.getAnimations().length),1);await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(70);assert.equal(await pet.evaluate(e=>e.getAnimations().length),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('.quote-mascot img').getAttribute('src'),'assets/akme-cat.webp');}
 await page.emulateMedia({reducedMotion:'no-preference'});await go('index.html');await page.locator('.impact-message').scrollIntoViewIfNeeded();await page.waitForTimeout(50);assert(await page.locator('.impact-message i').evaluateAll(es=>es.some(e=>e.getAnimations().length)));await page.waitForTimeout(1300);assert(await page.locator('.impact-message i').evaluateAll(es=>es.every(e=>getComputedStyle(e).transform==='none')));await page.locator('.message-replay').focus();await page.keyboard.press('Enter');assert(await page.locator('.impact-message i').evaluateAll(es=>es.some(e=>e.getAnimations().length)));await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(70);assert(await page.locator('.impact-message i').evaluateAll(es=>es.every(e=>e.getAnimations().length===0)));
 await go('servicios.html');assert.equal(await page.locator('.process-step').count(),4);assert.equal(await page.locator('.concept-tag').count(),3);for(let i=0;i<4;i++){await page.locator('#concept-step-'+i).evaluate(e=>scrollTo(0,e.offsetTop+e.offsetHeight/2-innerHeight*.52));await page.waitForTimeout(80);assert(await page.locator('#concept-step-'+i).evaluate(e=>e.classList.contains('is-current')));}await page.locator('.process-scope summary').click();assert.equal(await page.locator('.process-scope li').count(),4);assert.equal(await page.locator('.service-sample').count(),3);
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),touch=await context.newPage();await touch.goto(base+'portafolio.html');await touch.getByRole('button',{name:'Animar panda',exact:true}).tap();assert.equal(await touch.locator('.mascot-reactive').evaluate(e=>e.getAnimations().length),1);await touch.locator('#menu-btn').tap();await touch.locator('#navigation-dialog a[href="servicios.html"]').tap();await touch.waitForURL('**/servicios.html');await context.close();assert.deepEqual(errors,[]);console.log('PASS contextual gestures: one per page, 4 widths x4 pages, no autoplay, Enter/Space/touch, links, phrase scroll/replay, reduced motion, process highlighting/concept labels, service content retained, no JS errors.');
}finally{await browser.close();server.close();}
