import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};

const data=JSON.parse(fs.readFileSync('portfolio.json','utf8')),spa=data.find(b=>b.id==='spadental');
assert.equal(spa.items.length,5);assert.deepEqual(spa.items.slice(0,3).map(i=>i.title),['Limpieza dental','Acrílico parcial','Endodoncia']);
for(const width of [1920,1366,320,390,430]){
 await page.setViewportSize({width,height:1000});await go('portafolio.html#proyecto-spadental');await page.waitForFunction(()=>document.querySelector('#proyecto-spadental .gallery-bottom button')?.textContent.includes('5 piezas'));
 const section=page.locator('#proyecto-spadental');
 for(let i=0;i<3;i++){const card=section.locator('.gallery-card').nth(i);assert.equal(await card.getAttribute('href'),spa.items[i].src);await card.locator('img').evaluate(e=>{e.loading='eager';return e.decode()});assert.equal(await card.locator('img').evaluate(e=>getComputedStyle(e).objectFit),'contain');const box=await card.locator('.gallery-canvas').boundingBox();assert(Math.abs(box.width-box.height)<2);await card.focus();await page.keyboard.press('Enter');await page.locator('#gallery-media img').evaluate(e=>e.decode());assert((await page.locator('#gallery-title').textContent()).includes(spa.items[i].title));await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#gallery-count').textContent(),(i+2)+' de 5');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#gallery-viewer').open&&!history.state?.akmeGallery);await card.evaluate(e=>new Promise((resolve,reject)=>{let tries=0;const check=()=>{if(document.activeElement===e)return resolve();if(++tries>30)return reject(Error('Focus after close: '+document.activeElement.outerHTML.slice(0,250)));requestAnimationFrame(check)};check()}));}
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('#proyecto-canelitas').count(),1);await section.screenshot({path:'qa-output/spa-'+width+'.png'});
}
const nojs=await browser.newContext({javaScriptEnabled:false});const fallback=await nojs.newPage();await fallback.goto(base+'portafolio.html',{waitUntil:'domcontentloaded'});assert.deepEqual(await fallback.locator('#proyecto-spadental .gallery-card').evaluateAll(es=>es.map(e=>e.getAttribute('href'))),spa.items.slice(0,3).map(i=>i.src));await nojs.close();assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS Spa: 3 original previews, 5 pieces, keyboard/modal focus, square uncropped images, 5 responsive widths, Canelitas and no-JS fallback.');
