import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge'}),page=await browser.newPage({reducedMotion:'reduce'});const errors=[],missing=[],media=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(base))missing.push(r.url());});page.on('request',r=>{if(r.url().includes('.mp4'))media.push(r.url());});
const go=async f=>{await page.goto(base+f,{waitUntil:'domcontentloaded'});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode().catch(()=>{})}))});};
try{
for(const width of [1920,1366,320,390,430]){await page.setViewportSize({width,height:900});for(const file of ['index.html','portafolio.html','servicios.html','planes.html']){await go(file);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width+file);assert(await page.locator('h1').isVisible());if(file==='portafolio.html'){assert.equal(await page.locator('.gallery-card').count(),15);assert.equal(await page.locator('.editorial-dark.magazine-brand').count(),2);for(const card of await page.locator('.gallery-card').all())assert(await card.isVisible());const sizes=await page.locator('.gallery-card[data-format="video"] .gallery-canvas').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return r.width/r.height}));for(const ratio of sizes)assert(Math.abs(ratio-9/16)<.01,'Uniform video covers');}if([1920,390].includes(width))await page.screenshot({path:'qa-output/revista-'+file.replace('.html','')+'-'+width+'.png',fullPage:true});}console.log('PASS editorial layout '+width);}
await go('index.html');assert.equal(media.length,0,'No video bytes before interaction');const video=page.locator('#akme-showreel');assert.equal(await video.getAttribute('preload'),'none');await page.locator('[data-reel-play]').click();await page.waitForFunction(()=>document.getElementById('akme-showreel').currentTime>.1);const stats=await video.evaluate(v=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight,muted:v.muted}));assert(Math.abs(stats.duration-14)<.2,JSON.stringify(stats));assert.equal(stats.width,1280);await video.evaluate(v=>v.pause());assert(await page.locator('[data-reel-play]').isVisible());await video.evaluate(v=>{v.currentTime=v.duration-.2;return v.play()});await page.waitForFunction(()=>document.getElementById('akme-showreel').ended);assert(await page.locator('[data-reel-play]').isVisible());
await go('planes.html');for(const button of await page.locator('.plan-select').all()){await button.focus();await page.keyboard.press('Enter');assert.equal(await button.getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.plan.is-selected').count(),1);assert.equal(await page.locator('#quote-inspect').inputValue(),await button.getAttribute('data-plan'));assert.equal(await button.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(162, 212, 11)');}await page.locator('#quote-reset').click();assert.equal(await page.locator('#quote-name').textContent(),'SMART');assert.equal(await page.locator('.plan.is-selected').count(),0);
await go('portafolio.html');const card=page.locator('.gallery-card').first();await card.focus();await page.keyboard.press('Enter');assert(await page.locator('#gallery-viewer').isVisible());await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#gallery-viewer')?.open);assert(await card.evaluate(e=>e===document.activeElement));
await page.evaluate(()=>scrollTo(0,800));assert.equal(await page.evaluate(()=>document.getAnimations().length),0,'Reduced motion');
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const fallback=await nojs.newPage();await fallback.goto(base+'portafolio.html');assert.equal(await fallback.locator('.gallery-card').count(),15);assert(await fallback.locator('.menu-panel').isVisible());assert(await fallback.locator('.gallery-card').first().getAttribute('href'));await fallback.goto(base+'index.html');assert(await fallback.locator('#akme-showreel').getAttribute('controls')!==null);assert(!(await fallback.locator('[data-reel-play]').isVisible()));await fallback.goto(base+'planes.html');assert.equal(await fallback.locator('.plan').count(),5);await nojs.close();
function luminance(hex){return hex.match(/\w\w/g).map(n=>parseInt(n,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0)}for(const [fg,bg]of [['ffffff','171914'],['d1d3cc','171914'],['0d0d0f','a2d40b'],['4b4f44','ffffff']]){const a=luminance(fg),b=luminance(bg);assert((Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5);}
assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('PASS reel 14s/manual playback/end, plan keyboard selection, comparison, gallery keyboard/focus, reduced motion, no-JS fallback, contrast, no missing assets/JS errors; '+await browser.version());
}finally{await browser.close();server.close();}
