import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.mp3':'audio/mpeg'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
 let requested=0;page.on('request',r=>{if(r.url().includes('halloween-laugh.mp3'))requested++});await page.addInitScript(()=>{const Original=window.Audio;window.Audio=function(...args){const a=new Original(...args);window.testAudio=a;return a;};});
 await go('index.html');assert(await page.locator('.sound-yes').isVisible());await page.waitForTimeout(250);assert.equal(requested,0);assert(await page.evaluate(()=>testAudio.paused));await page.locator('.sound-no').click();assert(!(await page.locator('.halloween-welcome').isVisible()));assert.equal(requested,0);await page.reload();assert.equal(await page.locator('.halloween-welcome').count(),0);
 await page.evaluate(()=>sessionStorage.removeItem('akme:halloween-sound-choice'));await page.reload();await page.locator('.sound-yes').click();await page.waitForFunction(()=>window.testAudio&&!testAudio.paused&&testAudio.currentTime>.1);const info=await page.evaluate(()=>({duration:testAudio.duration,volume:testAudio.volume,loop:testAudio.loop}));assert(Math.abs(info.duration-9.56)<.1);assert.equal(info.volume,.35);assert.equal(info.loop,false);assert(await page.locator('.halloween-sound-control').isVisible());
 await page.locator('.halloween-sound-control').click();assert(await page.evaluate(()=>testAudio.paused));const position=await page.evaluate(()=>testAudio.currentTime);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>testAudio.currentTime),position);await page.locator('.halloween-sound-control').click();await page.waitForFunction(()=>!testAudio.paused);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.evaluate(()=>testAudio.paused));await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert(await page.evaluate(()=>testAudio.paused),'No automatic resume');await page.locator('.halloween-sound-control').click();await page.waitForFunction(()=>testAudio.ended,{},{timeout:15000});assert(!(await page.locator('.halloween-sound-control').isVisible()));assert(await page.evaluate(()=>testAudio.currentTime>=9.4));
 const count=requested;await go('planes.html');assert.equal(await page.locator('.halloween-welcome,.halloween-sound-control').count(),0);assert.equal(requested,count);await go('index.html');assert.equal(await page.locator('.halloween-welcome').count(),0);assert.equal(requested,count);
 for(const width of [320,390,1440]){await page.evaluate(()=>sessionStorage.removeItem('akme:halloween-sound-choice'));await page.setViewportSize({width,height:844});await go('index.html');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('.sound-yes').isVisible());assert(await page.locator('.sound-no').isVisible());await page.locator('.nav a').filter({hasText:/^Paquetes$/}).evaluate(e=>e.click());await page.waitForURL('**/planes.html');}
 assert.deepEqual(errors,[]);console.log('PASS original 9.56s MP3 complete; explicit opt-in; no audio request when silent; 35% volume; pause/resume; hidden tab pause without autoplay; once per visit; other pages silent; responsive and navigation unaffected');
}finally{await browser.close();server.close();}
