import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
 for(const width of [320,390,430,1366,1920])for(const file of ['index.html','portafolio.html','servicios.html','planes.html']){await page.setViewportSize({width,height:900});await go(file);await page.locator('.visual-progress').waitFor({state:'attached'});assert.equal(await page.locator('.demo-label').count(),0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width+' '+file);assert.equal(await page.locator('.nav [aria-current=page]').count(),1);if(width<761){await page.locator('#menu-btn').click();await page.waitForFunction(()=>document.querySelector('#navigation-dialog').open);assert(await page.locator('.visual-menu-close').isVisible());await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#navigation-dialog').open);assert(await page.locator('#menu-btn').evaluate(e=>document.activeElement===e));}if(file==='servicios.html'){assert.equal(await page.locator('.visual-depth-frame').count(),2);assert.equal(await page.locator('.service-sample').count(),3);}assert.equal(await page.locator('.mascot-reactive').count(),1);}
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),mp=await context.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base+'index.html');await mp.locator('#navigation-dialog').waitFor({state:'attached'});await mp.locator('#menu-btn').tap();await mp.keyboard.press('Tab');assert(await mp.locator('#navigation-dialog').evaluate(e=>e.contains(document.activeElement)));await mp.goBack();await mp.waitForFunction(()=>!document.querySelector('#navigation-dialog').open);await mp.goForward();await mp.waitForFunction(()=>document.querySelector('#navigation-dialog').open);await mp.locator('.visual-menu-close').tap();await mp.waitForFunction(()=>!document.querySelector('#navigation-dialog').open);await mp.locator('#menu-btn').tap();await mp.locator('.visual-menu a[href="servicios.html"]').tap();await mp.waitForURL('**/servicios.html');await mp.locator('#navigation-dialog').waitFor({state:'attached'});assert(await mp.evaluate(()=>!document.documentElement.classList.contains('visual-menu-open')));await context.close();
 await page.setViewportSize({width:1366,height:900});await go('planes.html');const prices=['1.800','2.500','3.900','4.900','7.000'];assert.deepEqual(await page.locator('.plans-grid .plan-price b').allTextContents(),prices);await page.locator('.plan-select[data-plan=pro]').click();assert(await page.locator('.visual-plans').evaluate(e=>e.classList.contains('has-visual-selection')));assert.equal(await page.locator('.plan-select[aria-pressed=true]').count(),1);assert.deepEqual(await page.locator('.plans-grid .plan-price b').allTextContents(),prices);await page.locator('#quote-reset').click();await page.waitForTimeout(80);assert.equal(await page.locator('.plan-select[aria-pressed=true]').count(),0);
 await go('servicios.html');await page.locator('#equipo').scrollIntoViewIfNeeded();assert(await page.locator('.visual-depth-frame img').evaluateAll(es=>es.every(e=>getComputedStyle(e).transform==='none')));await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForTimeout(100);assert(await page.locator('.visual-depth-frame img').evaluateAll(es=>es.every(e=>e.style.transform.includes('scale(1.055)'))));await page.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await page.waitForTimeout(150);assert.equal(await page.locator('.visual-progress').evaluate(e=>e.style.transform),'scaleX(1)');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(80);assert(await page.locator('.visual-depth-frame img').evaluateAll(es=>es.every(e=>getComputedStyle(e).transform==='none')));assert.deepEqual(errors,[]);console.log('PASS integrated six: 5 widths x4 pages; menu touch/keyboard/Escape/back/forward/focus/links; exact prices and reset; two photos/reduced motion; progress; approved contextual mascots; no overflow or JS errors.');
}finally{await browser.close();server.close();}
