import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/AKME-ESTUDIO/':`http://127.0.0.1:${server.address().port}/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
try{
for(const width of [1920,1366,320,390,430]){
 await page.setViewportSize({width,height:900});await go('servicios.html');await page.locator('.service-samples img').evaluateAll(async es=>Promise.all(es.map(e=>{e.loading='eager';return e.decode()})));
 assert.equal(await page.locator('.service-sample').count(),3);assert.equal(await page.locator('.sample-video img').count(),3);
 assert.deepEqual(await page.locator('.sample-kind').allTextContents(),['Fotografía','Video','Diseño']);
 assert(await page.locator('.quote-mascot').isVisible());assert.equal(await page.locator('.quote-mascot').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(0, 0, 0, 0)');assert.equal(await page.locator('.quote-mascot').evaluate(e=>getComputedStyle(e).flexDirection),'column');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('.service-samples').scrollIntoViewIfNeeded();await page.screenshot({path:'qa-output/produccion-'+width+'.png'});
 await go('portafolio.html');assert.equal(await page.locator('.gallery-play-label').count(),4);assert.equal(await page.locator('.gallery-canvas img:not([width]),.gallery-canvas img:not([height])').count(),0);
 const dims=await page.locator('.gallery-canvas').first().boundingBox();await page.locator('.gallery-canvas img').first().evaluate(e=>{e.loading='eager';return e.decode()});assert.deepEqual(await page.locator('.gallery-canvas').first().boundingBox(),dims);
}

await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'no-preference'});await go('index.html');await page.mouse.move(5,5);
await page.evaluate(()=>{window.sequence={gestures:[],cues:[],flashes:[],samples:[]};const original=Element.prototype.animate;Element.prototype.animate=function(...args){if(this.classList.contains('camera-figure'))sequence.gestures.push(performance.now());if(this.classList.contains('camera-glint'))sequence.flashes.push(performance.now());if(this.classList.contains('camera-cue')&&args[0][0].opacity===0)sequence.cues.push(performance.now());return original.apply(this,args)};setInterval(()=>{const f=document.querySelector('.camera-glint'),g=document.querySelector('.camera-figure'),b=document.querySelector('.quote-mascot span');if(Number(getComputedStyle(f).opacity)>.05)sequence.samples.push({transform:getComputedStyle(g).transform,button:b.getBoundingClientRect().toJSON()})},50);});
await page.waitForFunction(()=>sequence.flashes.length>=2,{},{timeout:50000});await page.waitForTimeout(1100);const evidence=await page.evaluate(()=>sequence);assert(evidence.samples.length>10);assert(evidence.samples.every(s=>s.transform==='none'||s.transform==='matrix(1, 0, 0, 1, 0, 0)'),'Gato quieto durante flash');assert(Math.abs(evidence.gestures[1]-evidence.gestures[0]-10000)<250);assert(evidence.flashes[0]-evidence.gestures[0]>=1950);assert(Math.abs(evidence.flashes[0]-evidence.cues[0]-1000)<100);const seasonal=await page.evaluate(()=>!!window.AKME_SEASON?.enabled);assert.equal(await page.locator('.camera-cue').textContent(),seasonal?'¡Boo! Sonreí':'Sonríe');assert.equal(await page.locator('.camera-cue').getAttribute('aria-hidden'),'true');assert.equal(new Set(evidence.samples.map(s=>JSON.stringify(s.button))).size,1);
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.camera-glint').evaluate(e=>e.getAnimations().length),0);assert.equal(await page.locator('.camera-glint').evaluate(e=>getComputedStyle(e).display),'none');await page.locator('.quote-mascot').focus();assert.match(await page.locator('.quote-mascot').getAttribute('href'),/^https:\/\/wa.me\/59157385254/);assert.equal(await page.locator('.quote-mascot img').getAttribute('src'),seasonal?'assets/akme-ghost.png':'assets/akme-cat.webp');
assert.deepEqual(errors,[]);console.log('PASS production: 3 service signatures, 5 widths, reserved image geometry, video affordances, seasonal mascot identity, 10s real cycle, gesture then cue 1s before stationary flash, stable button, reduced motion, WhatsApp link. Browser '+await browser.version());
}finally{await browser.close();server.close();}
